using System;

namespace MS.Internal.Interop;

[Flags]
internal enum IFILTER_INIT
{
	IFILTER_INIT_CANON_PARAGRAPHS = 1,
	IFILTER_INIT_HARD_LINE_BREAKS = 2,
	IFILTER_INIT_CANON_HYPHENS = 4,
	IFILTER_INIT_CANON_SPACES = 8,
	IFILTER_INIT_APPLY_INDEX_ATTRIBUTES = 0x10,
	IFILTER_INIT_APPLY_OTHER_ATTRIBUTES = 0x20,
	IFILTER_INIT_INDEXING_ONLY = 0x40,
	IFILTER_INIT_SEARCH_LINKS = 0x80,
	IFILTER_INIT_APPLY_CRAWL_ATTRIBUTES = 0x100,
	IFILTER_INIT_FILTER_OWNED_VALUE_OK = 0x200
}
