using System.Runtime.CompilerServices;

namespace System.Windows.Documents;

internal static class RtfControls
{
	public const uint RTK_TOGGLE = 1u;

	public const uint RTK_FLAG = 2u;

	public const uint RTK_VALUE = 4u;

	public const uint RTK_DESTINATION = 8u;

	public const uint RTK_SYMBOL = 16u;

	public const uint RTK_PARAM = 32u;

	public const uint RTK_TEXT = 64u;

	public const uint RTK_ACHARPROPS = 128u;

	public const uint RTK_CHARPROPS = 256u;

	public const uint RTK_PARAPROPS = 512u;

	public const uint RTK_OBJPROPS = 1024u;

	public const uint RTK_BOOKMARKPROPS = 2048u;

	public const uint RTK_SECTIONPROPS = 4096u;

	public const uint RTK_DOCPROPS = 8192u;

	public const uint RTK_FILEPROPS = 16384u;

	public const uint RTK_COMMENT = 32768u;

	public const uint RTK_STYLE = 65536u;

	public const uint RTK_FONTTABLE = 131072u;

	public const uint RTK_COLORTABLE = 262144u;

	public const uint RTK_BULLETS = 524288u;

	public const uint RTK_TABLEDEF = 1048576u;

	public const uint RTK_SHAPES = 2097152u;

	public const uint RTK_POSOBJ = 4194304u;

	public const uint RTK_BORDER = 8388608u;

	public const uint RTK_SHADING = 16777216u;

	public const uint RTK_PICT = 33554432u;

	public const uint RTK_FIELD = 67108864u;

	public const uint RTK_FORMFIELD = 134217728u;

	public const uint RTK_INDEX = 268435456u;

	public const uint RTK_DRAWOBJ = 536870912u;

	public const uint RTK_INFO = 1073741824u;

	public const uint RTK_LISTTABLE = 2147483648u;

	public const uint RTK_PICTPROPS = 2147483648u;

	public const uint RTK_CHARSET = 2147483648u;

	public const uint RTK_UNICODE = 2147483648u;

	public const uint RTK_TABS = 2147483648u;

	public const uint RTK_FOOTNOTES = 2147483648u;

	public const uint RTK_HIGHLIGHT = 2147483648u;

	public const uint RTK_FILETABLE = 2147483648u;

	public const uint RTK_HEADER = 2147483648u;

	public const uint RTK_OBJECTS = 2147483648u;

	public const uint RTK_PARATEXT = 2147483648u;

	public const uint RTK_SPECIAL = 2147483648u;

	public const uint RTK_SECTION = 2147483648u;

	public const uint RTK_TOC = 2147483648u;

	internal static RtfControlWordInfo[] ControlTable = new RtfControlWordInfo[1170]
	{
		new RtfControlWordInfo(RtfControlWord.Ctrl_AB, "ab", 129u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_ABSH, "absh", 4194308u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_ABSLOCK, "abslock", 4194306u),
		CreateCommonControlWord("absnoovrlp", 4194337u),
		CreateCommonControlWord("absw", 4194308u),
		CreateCommonControlWord("acaps", 129u),
		CreateCommonControlWord("acccomma", 257u),
		CreateCommonControlWord("accdot", 257u),
		CreateCommonControlWord("accnone", 257u),
		CreateCommonControlWord("acf", 132u),
		CreateCommonControlWord("additive", 65538u),
		CreateCommonControlWord("adjustright", 4098u),
		CreateCommonControlWord("adn", 132u),
		CreateCommonDocPropsControlWord("aenddoc"),
		CreateCommonDocPropsControlWord("aendnotes"),
		CreateCommonControlWord("aexpnd", 132u),
		CreateCommonControlWord("af", 132u),
		CreateCommonControlWord("affixed", 514u),
		CreateCommonControlWord("afs", 132u),
		CreateCommonDocPropsControlWord("aftnbj"),
		CreateCommonControlWord("aftncn", 8200u),
		CreateCommonDocPropsControlWord("aftnnalc"),
		CreateCommonDocPropsControlWord("aftnnar"),
		CreateCommonDocPropsControlWord("aftnnauc"),
		CreateCommonDocPropsControlWord("aftnnchi"),
		CreateCommonDocPropsControlWord("aftnnchosung"),
		CreateCommonDocPropsControlWord("aftnncnum"),
		CreateCommonDocPropsControlWord("aftnndbar"),
		CreateCommonDocPropsControlWord("aftnndbnum"),
		CreateCommonDocPropsControlWord("aftnndbnumd"),
		CreateCommonDocPropsControlWord("aftnndbnumk"),
		CreateCommonDocPropsControlWord("aftnndbnumt"),
		CreateCommonDocPropsControlWord("aftnnganada"),
		CreateCommonDocPropsControlWord("aftnngbnum"),
		CreateCommonDocPropsControlWord("aftnngbnumd"),
		CreateCommonDocPropsControlWord("aftnngbnumk"),
		CreateCommonDocPropsControlWord("aftnngbnuml"),
		CreateCommonDocPropsControlWord("aftnnrlc"),
		CreateCommonDocPropsControlWord("aftnnruc"),
		CreateCommonDocPropsControlWord("aftnnzodiac"),
		CreateCommonDocPropsControlWord("aftnnzodiacd"),
		CreateCommonDocPropsControlWord("aftnnzodiacl"),
		CreateCommonDocPropsControlWord("aftnrestart"),
		CreateCommonDocPropsControlWord("aftnrstcont"),
		CreateCommonControlWord("aftnsep", 8200u),
		CreateCommonControlWord("aftnsepc", 8200u),
		CreateCommonControlWord("aftnstart", 8196u),
		CreateCommonDocPropsControlWord("aftntj"),
		CreateCommonControlWord("ai", 129u),
		CreateCommonControlWord("alang", 132u),
		CreateCommonDocPropsControlWord("allprot"),
		CreateCommonDocPropsControlWord("alntblind"),
		CreateCommonControlWord("alt", 65538u),
		CreateCommonControlWord("animtext", 292u),
		CreateCommonControlWord("annotation", 32776u),
		CreateCommonDocPropsControlWord("annotprot"),
		new RtfControlWordInfo(RtfControlWord.Ctrl_ANSI, "ansi", 8194u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_ANSICPG, "ansicpg", 8228u),
		CreateCommonControlWord("aoutl", 129u),
		CreateCommonControlWord("ascaps", 129u),
		CreateCommonControlWord("ashad", 129u),
		CreateCommonControlWord("aspalpha", 513u),
		CreateCommonControlWord("aspnum", 513u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_ASTRIKE, "astrike", 129u),
		CreateCommonControlWord("atnauthor", 32776u),
		CreateCommonControlWord("atnicn", 32776u),
		CreateCommonControlWord("atnid", 32776u),
		CreateCommonControlWord("atnref", 32776u),
		CreateCommonControlWord("atntime", 32776u),
		CreateCommonControlWord("atrfend", 32776u),
		CreateCommonControlWord("atrfstart", 32776u),
		CreateCommonControlWord("aul", 129u),
		CreateCommonControlWord("auld", 129u),
		CreateCommonControlWord("auldb", 129u),
		CreateCommonControlWord("aulnone", 129u),
		CreateCommonControlWord("aulw", 129u),
		CreateCommonControlWord("aup", 132u),
		CreateCommonControlWord("author", 1073741832u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_B, "b", 257u),
		CreateCommonControlWord("background", 2097160u),
		CreateCommonDocPropsControlWord("bdbfhdr"),
		CreateCommonDocPropsControlWord("bdrrlswsix"),
		CreateCommonControlWord("bgbdiag", 16777730u),
		CreateCommonControlWord("bgcross", 16777730u),
		CreateCommonControlWord("bgdcross", 16777730u),
		CreateCommonControlWord("bgdkbdiag", 16777730u),
		CreateCommonControlWord("bgdkcross", 16777730u),
		CreateCommonControlWord("bgdkdcross", 16777730u),
		CreateCommonControlWord("bgdkfdiag", 16777730u),
		CreateCommonControlWord("bgdkhoriz", 16777730u),
		CreateCommonControlWord("bgdkvert", 16777730u),
		CreateCommonControlWord("bgfdiag", 16777730u),
		CreateCommonControlWord("bghoriz", 16777730u),
		CreateCommonControlWord("bgvert", 16777730u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_BIN, "bin", 2147483652u),
		CreateCommonControlWord("binfsxn", 4100u),
		CreateCommonControlWord("binsxn", 4100u),
		CreateCommonControlWord("bkmkcolf", 2052u),
		CreateCommonControlWord("bkmkcoll", 2052u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_BKMKEND, "bkmkend", 2056u),
		CreateCommonControlWord("bkmkpub", 1026u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_BKMKSTART, "bkmkstart", 2056u),
		CreateCommonControlWord("bliptag", 2147483684u),
		CreateCommonControlWord("blipuid", 2147483652u),
		CreateCommonControlWord("blipupi", 2147483684u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_BLUE, "blue", 262148u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_BOX, "box", 8389122u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRART, "brdrart", 8228u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRB, "brdrb", 8389122u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRBAR, "brdrbar", 8389122u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRBTW, "brdrbtw", 8389122u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRCF, "brdrcf", 8389124u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRDASH, "brdrdash", 8389122u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRDASHD, "brdrdashd", 578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRDASHDD, "brdrdashdd", 578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRDASHDOTSTR, "brdrdashdotstr", 578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRDASHSM, "brdrdashsm", 578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRDB, "brdrdb", 8389122u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRDOT, "brdrdot", 8389122u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_BRDREMBOSS, "brdremboss", 578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRENGRAVE, "brdrengrave", 578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRFRAME, "brdrframe", 8389122u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRHAIR, "brdrhair", 8389122u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRINSET, "brdrinset", 578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRL, "brdrl", 8389122u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_BRDROUTSET, "brdroutset", 578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRNIL, "brdrnil", 578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRTBL, "brdrtbl", 578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRR, "brdrr", 8389122u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRS, "brdrs", 8389122u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRSH, "brdrsh", 8389122u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRT, "brdrt", 8389122u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRTH, "brdrth", 8389122u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRTHTNLG, "brdrthtnlg", 578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRTHTNMG, "brdrthtnmg", 578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRTHTNSG, "brdrthtnsg", 578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRTNTHLG, "brdrtnthlg", 578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRTNTHMG, "brdrtnthmg", 578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRTNTHSG, "brdrtnthsg", 578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRTNTHTNLG, "brdrtnthtnlg", 578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRTNTHTNMG, "brdrtnthtnmg", 578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRTNTHTNSG, "brdrtnthtnsg", 578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRTRIPLE, "brdrtriple", 578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRW, "brdrw", 8389124u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRWAVY, "brdrwavy", 578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_BRDRWAVYDB, "brdrwavydb", 578u),
		CreateCommonDocPropsControlWord("brkfrm"),
		new RtfControlWordInfo(RtfControlWord.Ctrl_BRSP, "brsp", 8389124u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_BULLET, "bullet", 16u),
		CreateCommonControlWord("buptim", 1073741832u),
		CreateCommonControlWord("bxe", 268435458u),
		CreateCommonControlWord("caps", 257u),
		CreateCommonControlWord("category", 1073741832u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_CB, "cb", 260u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_CBPAT, "cbpat", 16777732u),
		CreateCommonControlWord("cchs", 260u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_CELL, "cell", 16u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_CELLX, "cellx", 1048580u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_CF, "cf", 260u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_CFPAT, "cfpat", 16777732u),
		CreateCommonControlWord("cgrid", 292u),
		CreateCommonControlWord("charscalex", 16777508u),
		CreateCommonControlWord("chatn", 16u),
		CreateCommonControlWord("chbgbdiag", 16777474u),
		CreateCommonControlWord("chbgcross", 16777474u),
		CreateCommonControlWord("chbgdcross", 16777474u),
		CreateCommonControlWord("chbgdkbdiag", 16777474u),
		CreateCommonControlWord("chbgdkcross", 16777474u),
		CreateCommonControlWord("chbgdkdcross", 16777474u),
		CreateCommonControlWord("chbgdkfdiag", 16777474u),
		CreateCommonControlWord("chbgdkhoriz", 16777474u),
		CreateCommonControlWord("chbgdkvert", 16777474u),
		CreateCommonControlWord("chbgfdiag", 16777474u),
		CreateCommonControlWord("chbghoriz", 16777474u),
		CreateCommonControlWord("chbgvert", 16777474u),
		CreateCommonControlWord("chbrdr", 16777474u),
		CreateCommonControlWord("chcbpat", 16777508u),
		CreateCommonControlWord("chcfpat", 16777508u),
		CreateCommonControlWord("chdate", 16u),
		CreateCommonControlWord("chdpa", 16u),
		CreateCommonControlWord("chdpl", 16u),
		CreateCommonControlWord("chftn", 16u),
		CreateCommonControlWord("chftnsep", 16u),
		CreateCommonControlWord("chftnsepc", 16u),
		CreateCommonControlWord("chpgn", 16u),
		CreateCommonControlWord("chshdng", 16777508u),
		CreateCommonControlWord("chtime", 16u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_CLBGBDIAG, "clbgbdiag", 1048578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_CLBGCROSS, "clbgcross", 1048578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_CLBGDCROSS, "clbgdcross", 1048578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_CLBGDKBDIAG, "clbgdkbdiag", 1048578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_CLBGDKCROSS, "clbgdkcross", 1048578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_CLBGDKDCROSS, "clbgdkdcross", 1048578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_CLBGDKFDIAG, "clbgdkfdiag", 1048578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_CLBGDKHOR, "clbgdkhor", 1048578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_CLBGDKVERT, "clbgdkvert", 1048578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_CLBGFDIAG, "clbgfdiag", 1048578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_CLBGHORIZ, "clbghoriz", 1048578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_CLBGVERT, "clbgvert", 1048578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_CLBRDRB, "clbrdrb", 1048578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_CLBRDRL, "clbrdrl", 1048578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_CLBRDRR, "clbrdrr", 1048578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_CLBRDRT, "clbrdrt", 1048578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_CLCBPAT, "clcbpat", 1048580u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_CLCFPAT, "clcfpat", 1048580u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_CLDGLL, "cldgll", 1048578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_CLDGLU, "cldglu", 1048578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_CLFITTEXT, "clfittext", 1048578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_CLFTSWIDTH, "clftswidth", 1048612u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_CLMGF, "clmgf", 1048578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_CLMRG, "clmrg", 1048578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_CLOWRAP, "clowrap", 1048610u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_CLPADB, "clpadb", 1048612u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_CLPADFB, "clpadfb", 1048612u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_CLPADFL, "clpadfl", 1048612u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_CLPADFR, "clpadfr", 1048612u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_CLPADFT, "clpadft", 1048612u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_CLPADL, "clpadl", 1048612u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_CLPADR, "clpadr", 1048612u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_CLPADT, "clpadt", 1048612u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_CLSHDNG, "clshdng", 1048580u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_CLSHDRAWNIL, "clshdrawnil", 1048580u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_CLTXBTLR, "cltxbtlr", 1048578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_CLTXLRTB, "cltxlrtb", 1048578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_CLTXLRTBV, "cltxlrtbv", 1048578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_CLTXTBRL, "cltxtbrl", 1048578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_CLTXTBRLV, "cltxtbrlv", 1048578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_CLVERTALB, "clvertalb", 1048578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_CLVERTALC, "clvertalc", 1048578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_CLVERTALT, "clvertalt", 1048578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_CLVMGF, "clvmgf", 1048578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_CLVMRG, "clvmrg", 1048578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_CLWWIDTH, "clwwidth", 1048612u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_COLLAPSED, "collapsed", 514u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_COLNO, "colno", 4100u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_COLORTBL, "colortbl", 262152u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_COLS, "cols", 4100u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_COLSR, "colsr", 4100u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_COLSX, "colsx", 4100u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_COLUMN, "column", 16u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_COLW, "colw", 4100u),
		CreateCommonControlWord("comment", 1073741832u),
		CreateCommonControlWord("company", 1073741832u),
		CreateCommonControlWord("cpg", 2147483652u),
		CreateCommonControlWord("crauth", 16777508u),
		CreateCommonControlWord("crdate", 16777508u),
		CreateCommonControlWord("creatim", 1073741832u),
		CreateCommonControlWord("cs", 260u),
		CreateCommonControlWord("ctrl", 65538u),
		CreateCommonControlWord("cts", 8228u),
		CreateCommonControlWord("cufi", 548u),
		CreateCommonControlWord("culi", 548u),
		CreateCommonControlWord("curi", 548u),
		CreateCommonDocPropsControlWord("cvmme"),
		CreateCommonControlWord("datafield", 67108872u),
		CreateCommonControlWord("date", 67108866u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_DBCH, "dbch", 130u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_DEFF, "deff", 131076u),
		CreateCommonDocPropsControlWord("defformat"),
		new RtfControlWordInfo(RtfControlWord.Ctrl_DEFLANG, "deflang", 8196u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_DEFLANGA, "deflanga", 8196u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_DEFLANGFE, "deflangfe", 8196u),
		CreateCommonControlWord("defshp", 33554434u),
		CreateCommonControlWord("deftab", 8196u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_DELETED, "deleted", 257u),
		CreateCommonControlWord("dfrauth", 2147483684u),
		CreateCommonControlWord("dfrdate", 2147483684u),
		CreateCommonControlWord("dfrmtxtx", 4194308u),
		CreateCommonControlWord("dfrmtxty", 4194308u),
		CreateCommonControlWord("dfrstart", 2147483652u),
		CreateCommonControlWord("dfrstop", 2147483652u),
		CreateCommonControlWord("dfrxst", 2147483652u),
		CreateCommonControlWord("dghorigin", 8228u),
		CreateCommonControlWord("dghshow", 8228u),
		CreateCommonControlWord("dghspace", 8228u),
		CreateCommonDocPropsControlWord("dgmargin"),
		CreateCommonDocPropsControlWord("dgsnap"),
		CreateCommonControlWord("dgvorigin", 8228u),
		CreateCommonControlWord("dgvshow", 8228u),
		CreateCommonControlWord("dgvspace", 8228u),
		CreateCommonControlWord("dibitmap", 2147483652u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_DN, "dn", 2147483652u),
		CreateCommonDocPropsControlWord("dntblnsbdb"),
		new RtfControlWordInfo(RtfControlWord.Ctrl_DO, "do", 536870920u),
		CreateCommonDrawObjControlWord("dobxcolumn"),
		CreateCommonDrawObjControlWord("dobxmargin"),
		CreateCommonDrawObjControlWord("dobxpage"),
		CreateCommonDrawObjControlWord("dobymargin"),
		CreateCommonDrawObjControlWord("dobypage"),
		CreateCommonDrawObjControlWord("dobypara"),
		CreateCommonControlWord("doccomm", 1073741832u),
		CreateCommonDocPropsControlWord("doctemp"),
		CreateCommonControlWord("doctype", 8228u),
		CreateCommonControlWord("docvar", 8200u),
		CreateCommonControlWord("dodhgt", 536870916u),
		CreateCommonDrawObjControlWord("dolock"),
		CreateCommonDrawObjControlWord("dpaendhol"),
		CreateCommonControlWord("dpaendl", 536870916u),
		CreateCommonDrawObjControlWord("dpaendsol"),
		CreateCommonControlWord("dpaendw", 536870916u),
		CreateCommonDrawObjControlWord("dparc"),
		CreateCommonDrawObjControlWord("dparcflipx"),
		CreateCommonDrawObjControlWord("dparcflipy"),
		CreateCommonDrawObjControlWord("dpastarthol"),
		CreateCommonControlWord("dpastartl", 536870916u),
		CreateCommonDrawObjControlWord("dpastartsol"),
		CreateCommonControlWord("dpastartw", 536870916u),
		CreateCommonDrawObjControlWord("dpcallout"),
		CreateCommonControlWord("dpcoa", 536870916u),
		CreateCommonDrawObjControlWord("dpcoaccent"),
		CreateCommonDrawObjControlWord("dpcobestfit"),
		CreateCommonDrawObjControlWord("dpcoborder"),
		CreateCommonControlWord("dpcodabs", 536870916u),
		CreateCommonDrawObjControlWord("dpcodbottom"),
		CreateCommonDrawObjControlWord("dpcodcenter"),
		CreateCommonControlWord("dpcodescent", 536870916u),
		CreateCommonDrawObjControlWord("dpcodtop"),
		CreateCommonControlWord("dpcolength", 536870916u),
		CreateCommonDrawObjControlWord("dpcominusx"),
		CreateCommonDrawObjControlWord("dpcominusy"),
		CreateCommonControlWord("dpcooffset", 536870916u),
		CreateCommonDrawObjControlWord("dpcosmarta"),
		CreateCommonDrawObjControlWord("dpcotdouble"),
		CreateCommonDrawObjControlWord("dpcotright"),
		CreateCommonDrawObjControlWord("dpcotsingle"),
		CreateCommonDrawObjControlWord("dpcottriple"),
		CreateCommonControlWord("dpcount", 536870916u),
		CreateCommonDrawObjControlWord("dpellipse"),
		CreateCommonDrawObjControlWord("dpendgroup"),
		CreateCommonControlWord("dpfillbgcb", 536870916u),
		CreateCommonControlWord("dpfillbgcg", 536870916u),
		CreateCommonControlWord("dpfillbgcr", 536870916u),
		CreateCommonControlWord("dpfillbggray", 536870916u),
		CreateCommonDrawObjControlWord("dpfillbgpal"),
		CreateCommonControlWord("dpfillfgcb", 536870916u),
		CreateCommonControlWord("dpfillfgcg", 536870916u),
		CreateCommonControlWord("dpfillfgcr", 536870916u),
		CreateCommonControlWord("dpfillfggray", 536870916u),
		CreateCommonDrawObjControlWord("dpfillfgpal"),
		CreateCommonControlWord("dpfillpat", 536870916u),
		CreateCommonDrawObjControlWord("dpgroup"),
		CreateCommonDrawObjControlWord("dpline"),
		CreateCommonControlWord("dplinecob", 536870916u),
		CreateCommonControlWord("dplinecog", 536870916u),
		CreateCommonControlWord("dplinecor", 536870916u),
		CreateCommonDrawObjControlWord("dplinedado"),
		CreateCommonDrawObjControlWord("dplinedadodo"),
		CreateCommonDrawObjControlWord("dplinedash"),
		CreateCommonDrawObjControlWord("dplinedot"),
		CreateCommonControlWord("dplinegray", 536870916u),
		CreateCommonDrawObjControlWord("dplinehollow"),
		CreateCommonDrawObjControlWord("dplinepal"),
		CreateCommonDrawObjControlWord("dplinesolid"),
		CreateCommonControlWord("dplinew", 536870916u),
		CreateCommonControlWord("dppolycount", 536870916u),
		CreateCommonDrawObjControlWord("dppolygon"),
		CreateCommonDrawObjControlWord("dppolyline"),
		CreateCommonControlWord("dpptx", 536870916u),
		CreateCommonControlWord("dppty", 536870916u),
		CreateCommonDrawObjControlWord("dprect"),
		CreateCommonDrawObjControlWord("dproundr"),
		CreateCommonDrawObjControlWord("dpshadow"),
		CreateCommonControlWord("dpshadx", 536870916u),
		CreateCommonControlWord("dpshady", 536870916u),
		CreateCommonDrawObjControlWord("dptxbtlr"),
		CreateCommonDrawObjControlWord("dptxbx"),
		CreateCommonControlWord("dptxbxmar", 536870916u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_DPTXBXTEXT, "dptxbxtext", 536870920u),
		CreateCommonDrawObjControlWord("dptxlrtb"),
		CreateCommonDrawObjControlWord("dptxlrtbv"),
		CreateCommonDrawObjControlWord("dptxtbrl"),
		CreateCommonDrawObjControlWord("dptxtbrlv"),
		CreateCommonControlWord("dpx", 536870916u),
		CreateCommonControlWord("dpxsize", 536870916u),
		CreateCommonControlWord("dpy", 536870916u),
		CreateCommonControlWord("dpysize", 536870916u),
		CreateCommonControlWord("dropcapli", 4194308u),
		CreateCommonControlWord("dropcapt", 4194308u),
		CreateCommonControlWord("ds", 4100u),
		CreateCommonControlWord("dxfrtext", 4194308u),
		CreateCommonControlWord("dy", 1073741828u),
		CreateCommonControlWord("edmins", 1073741828u),
		CreateCommonControlWord("embo", 16777473u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_EMDASH, "emdash", 16u),
		CreateCommonControlWord("emfblip", 33554434u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_EMSPACE, "emspace", 16u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_ENDASH, "endash", 16u),
		CreateCommonDocPropsControlWord("enddoc"),
		CreateCommonControlWord("endnhere", 4098u),
		CreateCommonDocPropsControlWord("endnotes"),
		new RtfControlWordInfo(RtfControlWord.Ctrl_ENSPACE, "enspace", 16u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_EXPND, "expnd", 260u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_EXPNDTW, "expndtw", 260u),
		CreateCommonDocPropsControlWord("expshrtn"),
		new RtfControlWordInfo(RtfControlWord.Ctrl_F, "f", 260u),
		CreateCommonControlWord("faauto", 516u),
		CreateCommonControlWord("facenter", 514u),
		CreateCommonDocPropsControlWord("facingp"),
		CreateCommonControlWord("fahang", 514u),
		CreateCommonControlWord("falt", 131080u),
		CreateCommonControlWord("faroman", 514u),
		CreateCommonControlWord("favar", 514u),
		CreateCommonControlWord("fbias", 131108u),
		CreateCommonControlWord("fbidi", 131074u),
		CreateCommonControlWord("fchars", 8200u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_FCHARSET, "fcharset", 131076u),
		CreateCommonControlWord("fdecor", 131074u),
		CreateCommonControlWord("fet", 8196u),
		CreateCommonControlWord("fetch", 131074u),
		CreateCommonControlWord("ffdefres", 134217732u),
		CreateCommonControlWord("ffdeftext", 134217736u),
		CreateCommonControlWord("ffentrymcr", 134217736u),
		CreateCommonControlWord("ffexitmcr", 134217736u),
		CreateCommonControlWord("ffformat", 134217736u),
		CreateCommonControlWord("ffhaslistbox", 134217764u),
		CreateCommonControlWord("ffhelptext", 134217736u),
		CreateCommonControlWord("ffhps", 134217764u),
		CreateCommonControlWord("ffl", 134217736u),
		CreateCommonControlWord("ffmaxlen", 134217732u),
		CreateCommonControlWord("ffname", 134217736u),
		CreateCommonControlWord("ffownhelp", 134217764u),
		CreateCommonControlWord("ffownstat", 134217764u),
		CreateCommonControlWord("ffprot", 134217764u),
		CreateCommonControlWord("ffrecalc", 134217764u),
		CreateCommonControlWord("ffres", 134217764u),
		CreateCommonControlWord("ffsize", 134217764u),
		CreateCommonControlWord("ffstattext", 134217736u),
		CreateCommonControlWord("fftype", 134217764u),
		CreateCommonControlWord("fftypetxt", 134217764u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_FI, "fi", 516u),
		CreateCommonControlWord("fid", 2147483652u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_FIELD, "field", 67108872u),
		CreateCommonControlWord("file", 2147483656u),
		CreateCommonControlWord("filetbl", 2147483656u),
		CreateCommonControlWord("fittext", 292u),
		CreateCommonDocPropsControlWord("fldalt"),
		CreateCommonControlWord("flddirty", 67108866u),
		CreateCommonControlWord("fldedit", 67108866u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_FLDINST, "fldinst", 67108872u),
		CreateCommonControlWord("fldlock", 67108866u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_FLDPRIV, "fldpriv", 67108866u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_FLDRSLT, "fldrslt", 67108872u),
		CreateCommonControlWord("fldtype", 67108872u),
		CreateCommonControlWord("fmodern", 131074u),
		CreateCommonControlWord("fn", 65540u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_FNAME, "fname", 131080u),
		CreateCommonControlWord("fnetwork", 2147483650u),
		CreateCommonControlWord("fnil", 2147483650u),
		CreateCommonControlWord("fontemb", 131080u),
		CreateCommonControlWord("fontfile", 131080u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_FONTTBL, "fonttbl", 131080u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_FOOTER, "footer", 2147483656u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_FOOTERF, "footerf", 2147483656u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_FOOTERL, "footerl", 2147483656u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_FOOTERR, "footerr", 2147483656u),
		CreateCommonControlWord("footery", 4100u),
		CreateCommonControlWord("footnote", 2147483656u),
		CreateCommonDocPropsControlWord("formdisp"),
		CreateCommonControlWord("formfield", 134217736u),
		CreateCommonDocPropsControlWord("formprot"),
		CreateCommonDocPropsControlWord("formshade"),
		CreateCommonControlWord("fosnum", 2147483652u),
		CreateCommonControlWord("fprq", 131076u),
		CreateCommonDocPropsControlWord("fracwidth"),
		CreateCommonControlWord("frelative", 2147483652u),
		CreateCommonControlWord("frmtxbtlr", 4194306u),
		CreateCommonControlWord("frmtxlrtb", 4194306u),
		CreateCommonControlWord("frmtxlrtbv", 4194306u),
		CreateCommonControlWord("frmtxtbrl", 4194306u),
		CreateCommonControlWord("frmtxtbrlv", 4194306u),
		CreateCommonControlWord("froman", 131074u),
		CreateCommonDocPropsControlWord("fromhtml"),
		CreateCommonDocPropsControlWord("fromtext"),
		new RtfControlWordInfo(RtfControlWord.Ctrl_FS, "fs", 260u),
		CreateCommonControlWord("fscript", 131074u),
		CreateCommonControlWord("fswiss", 131074u),
		CreateCommonDocPropsControlWord("ftnalt"),
		CreateCommonDocPropsControlWord("ftnbj"),
		CreateCommonControlWord("ftncn", 8200u),
		CreateCommonControlWord("ftnil", 131074u),
		CreateCommonDocPropsControlWord("ftnlytwnine"),
		CreateCommonDocPropsControlWord("ftnnalc"),
		CreateCommonDocPropsControlWord("ftnnar"),
		CreateCommonDocPropsControlWord("ftnnauc"),
		CreateCommonDocPropsControlWord("ftnnchi"),
		CreateCommonDocPropsControlWord("ftnnchosung"),
		CreateCommonDocPropsControlWord("ftnncnum"),
		CreateCommonDocPropsControlWord("ftnndbar"),
		CreateCommonDocPropsControlWord("ftnndbnum"),
		CreateCommonDocPropsControlWord("ftnndbnumd"),
		CreateCommonDocPropsControlWord("ftnndbnumk"),
		CreateCommonDocPropsControlWord("ftnndbnumt"),
		CreateCommonDocPropsControlWord("ftnnganada"),
		CreateCommonDocPropsControlWord("ftnngbnum"),
		CreateCommonDocPropsControlWord("ftnngbnumd"),
		CreateCommonDocPropsControlWord("ftnngbnumk"),
		CreateCommonDocPropsControlWord("ftnngbnuml"),
		CreateCommonDocPropsControlWord("ftnnrlc"),
		CreateCommonDocPropsControlWord("ftnnruc"),
		CreateCommonDocPropsControlWord("ftnnzodiac"),
		CreateCommonDocPropsControlWord("ftnnzodiacd"),
		CreateCommonDocPropsControlWord("ftnnzodiacl"),
		CreateCommonDocPropsControlWord("ftnrestart"),
		CreateCommonDocPropsControlWord("ftnrstcont"),
		CreateCommonDocPropsControlWord("ftnrstpg"),
		CreateCommonControlWord("ftnsep", 8200u),
		CreateCommonControlWord("ftnsepc", 8200u),
		CreateCommonControlWord("ftnstart", 8196u),
		CreateCommonDocPropsControlWord("ftntj"),
		CreateCommonControlWord("fttruetype", 131074u),
		CreateCommonControlWord("fvaliddos", 2147483650u),
		CreateCommonControlWord("fvalidhpfs", 2147483650u),
		CreateCommonControlWord("fvalidmac", 2147483650u),
		CreateCommonControlWord("fvalidntfs", 2147483650u),
		CreateCommonControlWord("g", 264u),
		CreateCommonControlWord("gcw", 260u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_GREEN, "green", 262148u),
		CreateCommonControlWord("gridtbl", 264u),
		CreateCommonControlWord("gutter", 8196u),
		CreateCommonDocPropsControlWord("gutterprl"),
		CreateCommonControlWord("guttersxn", 4100u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_HEADER, "header", 2147483656u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_HEADERF, "headerf", 2147483656u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_HEADERL, "headerl", 2147483656u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_HEADERR, "headerr", 2147483656u),
		CreateCommonControlWord("headery", 4100u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_HICH, "hich", 130u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_HIGHLIGHT, "highlight", 2147483652u),
		CreateCommonControlWord("hlfr", 2097156u),
		CreateCommonControlWord("hlinkbase", 1073741828u),
		CreateCommonControlWord("hlloc", 2097156u),
		CreateCommonControlWord("hlsrc", 2097156u),
		CreateCommonDocPropsControlWord("horzdoc"),
		CreateCommonControlWord("horzsect", 4098u),
		CreateCommonControlWord("hr", 1073741828u),
		CreateCommonDocPropsControlWord("htmautsp"),
		CreateCommonDocPropsControlWord("htmlbase"),
		CreateCommonControlWord("htmlrtf", 8193u),
		CreateCommonControlWord("htmltag", 8200u),
		CreateCommonControlWord("hyphauto", 8193u),
		CreateCommonControlWord("hyphcaps", 8193u),
		CreateCommonControlWord("hyphconsec", 8196u),
		CreateCommonControlWord("hyphhotz", 8196u),
		CreateCommonControlWord("hyphpar", 513u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_I, "i", 257u),
		CreateCommonControlWord("id", 1073741828u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_ILVL, "ilvl", 2147483652u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_IMPR, "impr", 16777473u),
		CreateCommonControlWord("info", 1073741832u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_INTBL, "intbl", 514u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_ITAP, "itap", 548u),
		CreateCommonControlWord("ixe", 268435458u),
		CreateCommonDocPropsControlWord("jcompress"),
		CreateCommonDocPropsControlWord("jexpand"),
		new RtfControlWordInfo(RtfControlWord.Ctrl_JPEGBLIP, "jpegblip", 33554434u),
		CreateCommonDocPropsControlWord("jsksu"),
		CreateCommonControlWord("keep", 514u),
		CreateCommonControlWord("keepn", 514u),
		CreateCommonControlWord("kerning", 260u),
		CreateCommonControlWord("keycode", 65544u),
		CreateCommonControlWord("keywords", 1073741832u),
		CreateCommonControlWord("ksulang", 8228u),
		CreateCommonDocPropsControlWord("landscape"),
		new RtfControlWordInfo(RtfControlWord.Ctrl_LANG, "lang", 260u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_LANGFE, "langfe", 292u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_LANGFENP, "langfenp", 292u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_LANGNP, "langnp", 292u),
		CreateCommonControlWord("lbr", 48u),
		CreateCommonControlWord("lchars", 8200u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_LDBLQUOTE, "ldblquote", 16u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_LEVEL, "level", 516u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_LEVELFOLLOW, "levelfollow", 2147483684u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_LEVELINDENT, "levelindent", 2147483684u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_LEVELJC, "leveljc", 2147483684u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_LEVELJCN, "leveljcn", 2147483684u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_LEVELLEGAL, "levellegal", 2147483684u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_LEVELNFC, "levelnfc", 2147483684u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_LEVELNFCN, "levelnfcn", 2147483684u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_LEVELNORESTART, "levelnorestart", 2147483684u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_LEVELNUMBERS, "levelnumbers", 2147483656u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_LEVELOLD, "levelold", 2147483684u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_LEVELPREV, "levelprev", 2147483684u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_LEVELPREVSPACE, "levelprevspace", 2147483684u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_LEVELSPACE, "levelspace", 2147483684u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_LEVELSTARTAT, "levelstartat", 2147483684u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_LEVELTEMPLATEID, "leveltemplateid", 2147483684u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_LEVELTEXT, "leveltext", 2147483652u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_LFOLEVEL, "lfolevel", 2147483656u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_LI, "li", 516u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_LINE, "line", 16u),
		CreateCommonControlWord("linebetcol", 4098u),
		CreateCommonControlWord("linecont", 4098u),
		CreateCommonControlWord("linemod", 4100u),
		CreateCommonControlWord("lineppage", 4098u),
		CreateCommonControlWord("linerestart", 4098u),
		CreateCommonControlWord("linestart", 8196u),
		CreateCommonControlWord("linestarts", 4100u),
		CreateCommonControlWord("linex", 4100u),
		CreateCommonControlWord("linkself", 2147483650u),
		CreateCommonDocPropsControlWord("linkstyles"),
		CreateCommonControlWord("linkval", 1073741828u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_LIN, "lin", 548u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_LISA, "lisa", 548u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_LISB, "lisb", 548u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_LIST, "list", 2147483650u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_LISTHYBRID, "listhybrid", 2147483650u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_LISTID, "listid", 2147483684u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_LISTLEVEL, "listlevel", 2147483656u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_LISTNAME, "listname", 2147483656u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_LISTOVERRIDE, "listoverride", 2147483656u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_LISTOVERRIDECOUNT, "listoverridecount", 2147483684u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_LISTOVERRIDEFORMAT, "listoverrideformat", 2147483684u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_LISTOVERRIDESTART, "listoverridestart", 2147483684u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_LISTPICTURE, "listpicture", 2147483656u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_LISTRESTARTHDN, "listrestarthdn", 2147483684u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_LISTSIMPLE, "listsimple", 2147483684u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_LISTTABLE, "listtable", 2147483656u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_LISTOVERRIDETABLE, "listoverridetable", 2147483656u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_LISTTEMPLATEID, "listtemplateid", 2147483684u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_LISTTEXT, "listtext", 2147483656u),
		CreateCommonDocPropsControlWord("lnbrkrule"),
		CreateCommonControlWord("lndscpsxn", 4098u),
		CreateCommonDocPropsControlWord("lnongrid"),
		new RtfControlWordInfo(RtfControlWord.Ctrl_LOCH, "loch", 130u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_LQUOTE, "lquote", 16u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_LS, "ls", 2147483652u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_LTRCH, "ltrch", 258u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_LTRDOC, "ltrdoc", 8194u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_LTRMARK, "ltrmark", 16u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_LTRPAR, "ltrpar", 514u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_LTRROW, "ltrrow", 1048578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_LTRSECT, "ltrsect", 4098u),
		CreateCommonDocPropsControlWord("lytcalctblwd"),
		CreateCommonDocPropsControlWord("lytexcttp"),
		CreateCommonDocPropsControlWord("lytprtmet"),
		CreateCommonDocPropsControlWord("lyttblrtgr"),
		new RtfControlWordInfo(RtfControlWord.Ctrl_MAC, "mac", 2147483650u),
		CreateCommonControlWord("macpict", 33554434u),
		CreateCommonDocPropsControlWord("makebackup"),
		CreateCommonControlWord("manager", 1073741832u),
		CreateCommonControlWord("margb", 8196u),
		CreateCommonControlWord("margbsxn", 4100u),
		CreateCommonControlWord("margl", 8196u),
		CreateCommonControlWord("marglsxn", 4100u),
		CreateCommonDocPropsControlWord("margmirror"),
		CreateCommonControlWord("margr", 8196u),
		CreateCommonControlWord("margrsxn", 4100u),
		CreateCommonControlWord("margt", 8196u),
		CreateCommonControlWord("margtsxn", 4100u),
		CreateCommonControlWord("mhtmltag", 8u),
		CreateCommonControlWord("min", 1073741828u),
		CreateCommonControlWord("mo", 1073741828u),
		CreateCommonDocPropsControlWord("msmcap"),
		new RtfControlWordInfo(RtfControlWord.Ctrl_NESTCELL, "nestcell", 1048592u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_NESTROW, "nestrow", 1048592u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_NESTTABLEPROPS, "nesttableprops", 1048584u),
		CreateCommonControlWord("nextfile", 8200u),
		CreateCommonDocPropsControlWord("nocolbal"),
		CreateCommonControlWord("nocwrap", 514u),
		CreateCommonDocPropsControlWord("noextrasprl"),
		CreateCommonControlWord("nofchars", 1073741828u),
		CreateCommonControlWord("nofcharsws", 1073741828u),
		CreateCommonControlWord("nofpages", 1073741828u),
		CreateCommonControlWord("nofwords", 1073741828u),
		CreateCommonDocPropsControlWord("nolead"),
		CreateCommonControlWord("noline", 514u),
		CreateCommonDocPropsControlWord("nolnhtadjtbl"),
		CreateCommonControlWord("nonesttables", 1048584u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_NONSHPPICT, "nonshppict", 33554434u),
		CreateCommonControlWord("nooverflow", 514u),
		CreateCommonControlWord("noproof", 258u),
		CreateCommonControlWord("nosectexpand", 258u),
		CreateCommonControlWord("nosnaplinegrid", 514u),
		CreateCommonDocPropsControlWord("nospaceforul"),
		new RtfControlWordInfo(RtfControlWord.Ctrl_NOSUPERSUB, "nosupersub", 258u),
		CreateCommonDocPropsControlWord("notabind"),
		CreateCommonDocPropsControlWord("noultrlspc"),
		CreateCommonControlWord("nowidctlpar", 514u),
		CreateCommonControlWord("nowrap", 4194306u),
		CreateCommonControlWord("nowwrap", 514u),
		CreateCommonDocPropsControlWord("noxlattoyen"),
		CreateCommonControlWord("objalias", 2147483656u),
		CreateCommonControlWord("objalign", 2147483652u),
		CreateCommonControlWord("objattph", 2147483650u),
		CreateCommonControlWord("objautlink", 2147483650u),
		CreateCommonControlWord("objclass", 2147483656u),
		CreateCommonControlWord("objcropb", 2147483652u),
		CreateCommonControlWord("objcropl", 2147483652u),
		CreateCommonControlWord("objcropr", 2147483652u),
		CreateCommonControlWord("objcropt", 2147483652u),
		CreateCommonControlWord("objdata", 2147483656u),
		CreateCommonControlWord("object", 2147483656u),
		CreateCommonControlWord("objemb", 2147483650u),
		CreateCommonControlWord("objh", 2147483652u),
		CreateCommonControlWord("objhtml", 2147483650u),
		CreateCommonControlWord("objicemb", 2147483650u),
		CreateCommonControlWord("objlink", 2147483650u),
		CreateCommonControlWord("objlock", 2147483650u),
		CreateCommonControlWord("objname", 2147483656u),
		CreateCommonControlWord("objocx", 2147483650u),
		CreateCommonControlWord("objpub", 2147483650u),
		CreateCommonControlWord("objscalex", 2147483652u),
		CreateCommonControlWord("objscaley", 2147483652u),
		CreateCommonControlWord("objsect", 2147483656u),
		CreateCommonControlWord("objsetsize", 2147483650u),
		CreateCommonControlWord("objsub", 2147483650u),
		CreateCommonControlWord("objtime", 2147483656u),
		CreateCommonControlWord("objtransy", 2147483652u),
		CreateCommonControlWord("objupdate", 2147483650u),
		CreateCommonControlWord("objw", 2147483652u),
		CreateCommonDocPropsControlWord("oldas"),
		CreateCommonDocPropsControlWord("oldlinewrap"),
		CreateCommonControlWord("operator", 1073741832u),
		CreateCommonDocPropsControlWord("otblrul"),
		new RtfControlWordInfo(RtfControlWord.Ctrl_OUTL, "outl", 257u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_OUTLINELEVEL, "outlinelevel", 2147483684u),
		CreateCommonControlWord("overlay", 578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_PAGE, "page", 16u),
		CreateCommonControlWord("pagebb", 514u),
		CreateCommonControlWord("panose", 131080u),
		CreateCommonControlWord("paperh", 8196u),
		CreateCommonControlWord("paperw", 8196u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_PAR, "par", 16u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_PARD, "pard", 514u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_PC, "pc", 2147483650u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_PCA, "pca", 2147483650u),
		CreateCommonDocPropsControlWord("pgbrdrb"),
		CreateCommonDocPropsControlWord("pgbrdrfoot"),
		CreateCommonDocPropsControlWord("pgbrdrhead"),
		CreateCommonDocPropsControlWord("pgbrdrl"),
		CreateCommonControlWord("pgbrdropt", 8228u),
		CreateCommonDocPropsControlWord("pgbrdrr"),
		CreateCommonDocPropsControlWord("pgbrdrsnap"),
		CreateCommonDocPropsControlWord("pgbrdrt"),
		CreateCommonControlWord("pghsxn", 4100u),
		CreateCommonControlWord("pgnbidia", 4098u),
		CreateCommonControlWord("pgnbidib", 4098u),
		CreateCommonControlWord("pgnchosung", 524290u),
		CreateCommonControlWord("pgncnum", 524290u),
		CreateCommonControlWord("pgncont", 4098u),
		CreateCommonControlWord("pgndbnum", 4098u),
		CreateCommonControlWord("pgndbnumd", 4098u),
		CreateCommonControlWord("pgndbnumk", 524290u),
		CreateCommonControlWord("pgndbnumt", 524290u),
		CreateCommonControlWord("pgndec", 4098u),
		CreateCommonControlWord("pgndecd", 4098u),
		CreateCommonControlWord("pgnganada", 524290u),
		CreateCommonControlWord("pgngbnum", 524290u),
		CreateCommonControlWord("pgngbnumd", 524290u),
		CreateCommonControlWord("pgngbnumk", 524290u),
		CreateCommonControlWord("pgngbnuml", 524290u),
		CreateCommonControlWord("pgnhn", 4100u),
		CreateCommonControlWord("pgnhnsc", 4098u),
		CreateCommonControlWord("pgnhnsh", 4098u),
		CreateCommonControlWord("pgnhnsm", 4098u),
		CreateCommonControlWord("pgnhnsn", 4098u),
		CreateCommonControlWord("pgnhnsp", 4098u),
		CreateCommonControlWord("pgnlcltr", 4098u),
		CreateCommonControlWord("pgnlcrm", 4098u),
		CreateCommonControlWord("pgnrestart", 4098u),
		CreateCommonControlWord("pgnstart", 8196u),
		CreateCommonControlWord("pgnstarts", 4100u),
		CreateCommonControlWord("pgnucltr", 4098u),
		CreateCommonControlWord("pgnucrm", 4098u),
		CreateCommonControlWord("pgnx", 4100u),
		CreateCommonControlWord("pgny", 4100u),
		CreateCommonControlWord("pgnzodiac", 524290u),
		CreateCommonControlWord("pgnzodiacd", 524290u),
		CreateCommonControlWord("pgnzodiacl", 524290u),
		CreateCommonControlWord("pgwsxn", 4100u),
		CreateCommonControlWord("phcol", 4194306u),
		CreateCommonControlWord("phmrg", 4194306u),
		CreateCommonControlWord("phpg", 4194306u),
		CreateCommonControlWord("picbmp", 33554434u),
		CreateCommonControlWord("picbpp", 2147483652u),
		CreateCommonControlWord("piccropb", 2147483652u),
		CreateCommonControlWord("piccropl", 2147483652u),
		CreateCommonControlWord("piccropr", 2147483652u),
		CreateCommonControlWord("piccropt", 2147483652u),
		CreateCommonControlWord("pich", 2147483652u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_PICHGOAL, "pichgoal", 2147483652u),
		CreateCommonControlWord("picprop", 33554440u),
		CreateCommonControlWord("picscaled", 33554434u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_PICSCALEX, "picscalex", 2147483652u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_PICSCALEY, "picscaley", 2147483652u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_PICT, "pict", 33554440u),
		CreateCommonControlWord("picw", 2147483652u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_PICWGOAL, "picwgoal", 2147483652u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_PLAIN, "plain", 258u),
		CreateCommonControlWord("pmmetafile", 2147483652u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_PN, "pn", 524296u),
		CreateCommonControlWord("pnacross", 524290u),
		CreateCommonControlWord("pnaiu", 524290u),
		CreateCommonControlWord("pnaiud", 524290u),
		CreateCommonControlWord("pnaiueo", 524290u),
		CreateCommonControlWord("pnaiueod", 524290u),
		CreateCommonControlWord("pnb", 524289u),
		CreateCommonControlWord("pnbidia", 524290u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_PNBIDIB, "pnbidib", 524290u),
		CreateCommonControlWord("pncaps", 524289u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_PNCARD, "pncard", 524290u),
		CreateCommonControlWord("pncf", 524292u),
		CreateCommonControlWord("pnchosung", 524290u),
		CreateCommonControlWord("pncnum", 524290u),
		CreateCommonControlWord("pndbnum", 524290u),
		CreateCommonControlWord("pndbnumd", 524290u),
		CreateCommonControlWord("pndbnumk", 524290u),
		CreateCommonControlWord("pndbnuml", 524290u),
		CreateCommonControlWord("pndbnumt", 524290u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_PNDEC, "pndec", 524290u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_PNDECD, "pndecd", 524290u),
		CreateCommonControlWord("pnf", 524292u),
		CreateCommonControlWord("pnfs", 524292u),
		CreateCommonControlWord("pnganada", 524290u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_PNGBLIP, "pngblip", 33554434u),
		CreateCommonControlWord("pngbnum", 524290u),
		CreateCommonControlWord("pngbnumd", 524290u),
		CreateCommonControlWord("pngbnumk", 524290u),
		CreateCommonControlWord("pngbnuml", 524290u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_PNHANG, "pnhang", 524290u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_PNI, "pni", 524289u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_PNINDENT, "pnindent", 524292u),
		CreateCommonControlWord("pniroha", 524290u),
		CreateCommonControlWord("pnirohad", 524290u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_PNLCLTR, "pnlcltr", 524290u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_PNLCRM, "pnlcrm", 524290u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_PNLVL, "pnlvl", 524292u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_PNLVLBLT, "pnlvlblt", 524290u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_PNLVLBODY, "pnlvlbody", 524290u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_PNLVLCONT, "pnlvlcont", 524290u),
		CreateCommonControlWord("pnnumonce", 524290u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_PNORD, "pnord", 524290u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_PNORDT, "pnordt", 524290u),
		CreateCommonControlWord("pnprev", 524290u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_PNQC, "pnqc", 524290u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_PNQL, "pnql", 524290u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_PNQR, "pnqr", 524290u),
		CreateCommonControlWord("pnrauth", 2147483684u),
		CreateCommonControlWord("pnrdate", 2147483684u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_PNRESTART, "pnrestart", 524290u),
		CreateCommonControlWord("pnrnfc", 2147483684u),
		CreateCommonControlWord("pnrnot", 578u),
		CreateCommonControlWord("pnrpnbr", 2147483684u),
		CreateCommonControlWord("pnrrgb", 2147483684u),
		CreateCommonControlWord("pnrstart", 2147483684u),
		CreateCommonControlWord("pnrstop", 2147483684u),
		CreateCommonControlWord("pnrxst", 2147483684u),
		CreateCommonControlWord("pnscaps", 524289u),
		CreateCommonControlWord("pnseclvl", 524296u),
		CreateCommonControlWord("pnsp", 524292u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_PNSTART, "pnstart", 524292u),
		CreateCommonControlWord("pnstrike", 524289u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_PNTEXT, "pntext", 524296u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_PNTXTA, "pntxta", 524296u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_PNTXTB, "pntxtb", 524296u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_PNUCLTR, "pnucltr", 524290u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_PNUCRM, "pnucrm", 524290u),
		CreateCommonControlWord("pnul", 524289u),
		CreateCommonControlWord("pnuld", 524290u),
		CreateCommonControlWord("pnuldash", 524290u),
		CreateCommonControlWord("pnuldashd", 524290u),
		CreateCommonControlWord("pnuldashdd", 524290u),
		CreateCommonControlWord("pnuldb", 524290u),
		CreateCommonControlWord("pnulhair", 524290u),
		CreateCommonControlWord("pnulnone", 524290u),
		CreateCommonControlWord("pnulth", 524290u),
		CreateCommonControlWord("pnulw", 524290u),
		CreateCommonControlWord("pnulwave", 524290u),
		CreateCommonControlWord("pnzodiac", 524290u),
		CreateCommonControlWord("pnzodiacd", 524290u),
		CreateCommonControlWord("pnzodiacl", 524290u),
		CreateCommonControlWord("posnegx", 4194308u),
		CreateCommonControlWord("posnegy", 4194308u),
		CreateCommonControlWord("posx", 4194308u),
		CreateCommonControlWord("posxc", 4194306u),
		CreateCommonControlWord("posxi", 4194306u),
		CreateCommonControlWord("posxl", 4194306u),
		CreateCommonControlWord("posxo", 4194306u),
		CreateCommonControlWord("posxr", 4194306u),
		CreateCommonControlWord("posy", 4194308u),
		CreateCommonControlWord("posyb", 4194306u),
		CreateCommonControlWord("posyc", 4194306u),
		CreateCommonControlWord("posyil", 4194306u),
		CreateCommonControlWord("posyin", 578u),
		CreateCommonControlWord("posyout", 578u),
		CreateCommonControlWord("posyt", 4194306u),
		CreateCommonDocPropsControlWord("prcolbl"),
		CreateCommonDocPropsControlWord("printdata"),
		CreateCommonControlWord("printim", 1073741832u),
		CreateCommonControlWord("private", 8200u),
		CreateCommonControlWord("propname", 1073741828u),
		CreateCommonControlWord("proptype", 1073741828u),
		CreateCommonDocPropsControlWord("psover"),
		CreateCommonControlWord("psz", 8196u),
		CreateCommonControlWord("pubauto", 1026u),
		CreateCommonControlWord("pvmrg", 4194306u),
		CreateCommonControlWord("pvpara", 4194306u),
		CreateCommonControlWord("pvpg", 4194306u),
		CreateCommonControlWord("pwd", 40u),
		CreateCommonControlWord("pxe", 268435464u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_QC, "qc", 514u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_QD, "qd", 514u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_QJ, "qj", 514u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_QL, "ql", 514u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_QMSPACE, "qmspace", 16u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_QR, "qr", 514u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_RDBLQUOTE, "rdblquote", 16u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_RED, "red", 262148u),
		CreateCommonControlWord("result", 2147483656u),
		CreateCommonControlWord("revauth", 260u),
		CreateCommonControlWord("revauthdel", 16777508u),
		CreateCommonControlWord("revbar", 8196u),
		CreateCommonControlWord("revdttm", 260u),
		CreateCommonControlWord("revdttmdel", 16777508u),
		CreateCommonControlWord("revised", 257u),
		CreateCommonDocPropsControlWord("revisions"),
		CreateCommonControlWord("revprop", 8196u),
		CreateCommonDocPropsControlWord("revprot"),
		CreateCommonControlWord("revtbl", 8u),
		CreateCommonControlWord("revtim", 1073741832u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_RI, "ri", 516u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_RIN, "rin", 548u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_ROW, "row", 16u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_RQUOTE, "rquote", 16u),
		CreateCommonControlWord("rsltbmp", 2147483650u),
		CreateCommonControlWord("rslthtml", 2147483650u),
		CreateCommonControlWord("rsltmerge", 2147483650u),
		CreateCommonControlWord("rsltpict", 2147483650u),
		CreateCommonControlWord("rsltrtf", 2147483650u),
		CreateCommonControlWord("rslttxt", 2147483650u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_RTF, "rtf", 16384u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_RTLCH, "rtlch", 258u),
		CreateCommonDocPropsControlWord("rtldoc"),
		CreateCommonDocPropsControlWord("rtlgutter"),
		new RtfControlWordInfo(RtfControlWord.Ctrl_RTLMARK, "rtlmark", 16u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_RTLPAR, "rtlpar", 514u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_RTLROW, "rtlrow", 1048578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_RTLSECT, "rtlsect", 4098u),
		CreateCommonControlWord("rxe", 268435464u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_S, "s", 516u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_SA, "sa", 516u),
		CreateCommonControlWord("saauto", 545u),
		CreateCommonControlWord("sautoupd", 65538u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_SB, "sb", 516u),
		CreateCommonControlWord("sbasedon", 65540u),
		CreateCommonControlWord("sbauto", 545u),
		CreateCommonControlWord("sbkcol", 4098u),
		CreateCommonControlWord("sbkeven", 4098u),
		CreateCommonControlWord("sbknone", 4098u),
		CreateCommonControlWord("sbkodd", 4098u),
		CreateCommonControlWord("sbkpage", 4098u),
		CreateCommonControlWord("sbys", 514u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_SCAPS, "scaps", 257u),
		CreateCommonControlWord("scompose", 65538u),
		CreateCommonControlWord("sec", 1073741828u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_SECT, "sect", 16u),
		CreateCommonControlWord("sectd", 4098u),
		CreateCommonControlWord("sectdefaultcl", 4100u),
		CreateCommonControlWord("sectexpand", 4132u),
		CreateCommonControlWord("sectlinegrid", 4132u),
		CreateCommonControlWord("sectnum", 16u),
		CreateCommonControlWord("sectspecifycl", 4100u),
		CreateCommonControlWord("sectspecifygen", 4130u),
		CreateCommonControlWord("sectspecifyl", 4100u),
		CreateCommonControlWord("sectunlocked", 4098u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_SHAD, "shad", 257u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_SHADING, "shading", 16777732u),
		CreateCommonControlWord("shidden", 65538u),
		CreateCommonControlWord("shift", 65538u),
		CreateCommonControlWord("shpbottom", 2097188u),
		CreateCommonControlWord("shpbxcolumn", 2097154u),
		CreateCommonControlWord("shpbxignore", 2097154u),
		CreateCommonControlWord("shpbxmargin", 2097154u),
		CreateCommonControlWord("shpbxpage", 2097154u),
		CreateCommonControlWord("shpbyignore", 2097154u),
		CreateCommonControlWord("shpbymargin", 2097154u),
		CreateCommonControlWord("shpbypage", 2097154u),
		CreateCommonControlWord("shpbypara", 2097154u),
		CreateCommonControlWord("shpfblwtxt", 2097188u),
		CreateCommonControlWord("shpfhdr", 2097188u),
		CreateCommonControlWord("shpgrp", 2097156u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_SHPINST, "shpinst", 2097160u),
		CreateCommonControlWord("shpleft", 2097188u),
		CreateCommonControlWord("shplid", 2097188u),
		CreateCommonControlWord("shplockanchor", 2097154u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_SHPPICT, "shppict", 33554440u),
		CreateCommonControlWord("shpright", 2097188u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_SHPRSLT, "shprslt", 2097156u),
		CreateCommonControlWord("shptop", 2097188u),
		CreateCommonControlWord("shptxt", 2097156u),
		CreateCommonControlWord("shpwrk", 2097188u),
		CreateCommonControlWord("shpwr", 2097188u),
		CreateCommonControlWord("shpz", 2097188u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_SL, "sl", 516u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_SLMULT, "slmult", 516u),
		CreateCommonControlWord("snext", 65540u),
		CreateCommonControlWord("softcol", 2147483650u),
		CreateCommonControlWord("softlheight", 2147483652u),
		CreateCommonControlWord("softline", 2147483650u),
		CreateCommonControlWord("softpage", 2147483650u),
		CreateCommonControlWord("spersonal", 65538u),
		CreateCommonDocPropsControlWord("splytwnine"),
		CreateCommonDocPropsControlWord("sprsbsp"),
		CreateCommonDocPropsControlWord("sprslnsp"),
		CreateCommonDocPropsControlWord("sprsspbf"),
		CreateCommonDocPropsControlWord("sprstsm"),
		CreateCommonDocPropsControlWord("sprstsp"),
		CreateCommonControlWord("sreply", 65538u),
		CreateCommonControlWord("staticval", 1073741828u),
		CreateCommonControlWord("stextflow", 2147483652u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_STRIKE, "strike", 257u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_STRIKED, "striked", 16777473u),
		CreateCommonControlWord("stylesheet", 65544u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_SUB, "sub", 258u),
		CreateCommonControlWord("subdocument", 516u),
		CreateCommonDocPropsControlWord("subfontbysize"),
		CreateCommonControlWord("subject", 1073741832u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_SUPER, "super", 258u),
		CreateCommonDocPropsControlWord("swpbdr"),
		new RtfControlWordInfo(RtfControlWord.Ctrl_TAB, "tab", 16u),
		CreateCommonControlWord("tabsnoovrlp", 1048578u),
		CreateCommonControlWord("taprtl", 1048578u),
		CreateCommonControlWord("tb", 2147483652u),
		CreateCommonControlWord("tc", 2147483656u),
		CreateCommonControlWord("tcelld", 1048578u),
		CreateCommonControlWord("tcf", 2147483652u),
		CreateCommonControlWord("tcl", 2147483652u),
		CreateCommonControlWord("tcn", 2147483650u),
		CreateCommonControlWord("tdfrmtxtbottom", 1048612u),
		CreateCommonControlWord("tdfrmtxtleft", 1048612u),
		CreateCommonControlWord("tdfrmtxtright", 1048612u),
		CreateCommonControlWord("tdfrmtxttop", 1048612u),
		CreateCommonControlWord("template", 8200u),
		CreateCommonControlWord("time", 67108866u),
		CreateCommonControlWord("title", 1073741832u),
		CreateCommonControlWord("titlepg", 4098u),
		CreateCommonControlWord("tldot", 2147483650u),
		CreateCommonControlWord("tleq", 2147483650u),
		CreateCommonControlWord("tlhyph", 2147483650u),
		CreateCommonControlWord("tlmdot", 2147483650u),
		CreateCommonControlWord("tlth", 2147483650u),
		CreateCommonControlWord("tlul", 2147483650u),
		CreateCommonControlWord("tphcol", 1048578u),
		CreateCommonControlWord("tphmrg", 1048578u),
		CreateCommonControlWord("tphpg", 1048578u),
		CreateCommonControlWord("tposnegx", 1048612u),
		CreateCommonControlWord("tposnegy", 1048612u),
		CreateCommonControlWord("tposxc", 1048578u),
		CreateCommonControlWord("tposxi", 1048578u),
		CreateCommonControlWord("tposxl", 1048578u),
		CreateCommonControlWord("tposx", 1048612u),
		CreateCommonControlWord("tposxo", 1048578u),
		CreateCommonControlWord("tposxr", 1048578u),
		CreateCommonControlWord("tposy", 1048578u),
		CreateCommonControlWord("tposyb", 1048578u),
		CreateCommonControlWord("tposyc", 1048578u),
		CreateCommonControlWord("tposyil", 1048578u),
		CreateCommonControlWord("tposyin", 1048578u),
		CreateCommonControlWord("tposyoutv", 1048578u),
		CreateCommonControlWord("tposyt", 1048578u),
		CreateCommonControlWord("tpvmrg", 1048578u),
		CreateCommonControlWord("tpvpara", 1048578u),
		CreateCommonControlWord("tpvpg", 1048578u),
		CreateCommonControlWord("tqc", 2147483650u),
		CreateCommonControlWord("tqdec", 2147483650u),
		CreateCommonControlWord("tqr", 2147483650u),
		CreateCommonDocPropsControlWord("transmf"),
		new RtfControlWordInfo(RtfControlWord.Ctrl_TRAUTOFIT, "trautofit", 1048609u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_TRBRDRB, "trbrdrb", 1048578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_TRBRDRH, "trbrdrh", 1048578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_TRBRDRL, "trbrdrl", 1048578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_TRBRDRR, "trbrdrr", 1048578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_TRBRDRT, "trbrdrt", 1048578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_TRBRDRV, "trbrdrv", 1048578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_TRFTSWIDTHA, "trftswidtha", 1048612u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_TRFTSWIDTHB, "trftswidthb", 1048612u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_TRFTSWIDTH, "trftswidth", 1048612u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_TRGAPH, "trgaph", 1048580u),
		CreateCommonControlWord("trhdr", 1048578u),
		CreateCommonControlWord("trkeep", 1048578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_TRLEFT, "trleft", 1048580u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_TROWD, "trowd", 1048578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_TRPADDB, "trpaddb", 1048612u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_TRPADDFB, "trpaddfb", 1048612u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_TRPADDFL, "trpaddfl", 1048612u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_TRPADDFR, "trpaddfr", 1048612u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_TRPADDFT, "trpaddft", 1048612u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_TRPADDL, "trpaddl", 1048612u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_TRPADDR, "trpaddr", 1048612u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_TRPADDT, "trpaddt", 1048612u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_TRQC, "trqc", 1048578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_TRQL, "trql", 1048578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_TRQR, "trqr", 1048578u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_TRRH, "trrh", 1048580u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_TRSPDB, "trspdb", 1048612u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_TRSPDFB, "trspdfb", 1048612u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_TRSPDFL, "trspdfl", 1048612u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_TRSPDFR, "trspdfr", 1048612u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_TRSPDFT, "trspdft", 1048612u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_TRSPDL, "trspdl", 1048612u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_TRSPDR, "trspdr", 1048612u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_TRSPDT, "trspdt", 1048612u),
		CreateCommonDocPropsControlWord("truncatefontheight"),
		new RtfControlWordInfo(RtfControlWord.Ctrl_TRWWIDTHA, "trwwidtha", 1048612u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_TRWWIDTHB, "trwwidthb", 1048612u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_TRWWIDTH, "trwwidth", 1048612u),
		CreateCommonDocPropsControlWord("twoonone"),
		CreateCommonControlWord("tx", 2147483652u),
		CreateCommonControlWord("txe", 268435464u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_UC, "uc", 2147483684u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_UD, "ud", 2147483656u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_UL, "ul", 257u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_ULC, "ulc", 292u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_ULD, "uld", 258u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_ULDASH, "uldash", 257u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_ULDASHD, "uldashd", 257u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_ULDASHDD, "uldashdd", 257u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_ULDB, "uldb", 257u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_ULHAIR, "ulhair", 257u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_ULHWAVE, "ulhwave", 257u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_ULLDASH, "ulldash", 257u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_ULNONE, "ulnone", 258u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_ULTH, "ulth", 257u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_ULTHD, "ulthd", 257u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_ULTHDASH, "ulthdash", 257u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_ULTHDASHD, "ulthdashd", 257u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_ULTHDASHDD, "ulthdashdd", 257u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_ULTHLDASH, "ulthldash", 257u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_ULULDBWAVE, "ululdbwave", 257u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_ULW, "ulw", 258u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_ULWAVE, "ulwave", 257u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_U, "u", 2147483684u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_UP, "up", 260u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_UPR, "upr", 2147483656u),
		CreateCommonControlWord("urtf", 40u),
		CreateCommonDocPropsControlWord("useltbaln"),
		CreateCommonControlWord("userprops", 1073741832u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_V, "v", 257u),
		CreateCommonControlWord("vern", 1073741828u),
		CreateCommonControlWord("version", 1073741828u),
		CreateCommonControlWord("vertalb", 4098u),
		CreateCommonControlWord("vertalc", 4098u),
		CreateCommonControlWord("vertalj", 4098u),
		CreateCommonControlWord("vertalt", 4098u),
		CreateCommonDocPropsControlWord("vertdoc"),
		CreateCommonControlWord("vertsect", 4098u),
		CreateCommonControlWord("viewkind", 8228u),
		CreateCommonControlWord("viewscale", 8228u),
		CreateCommonControlWord("viewzk", 8228u),
		CreateCommonControlWord("wbitmap", 2147483652u),
		CreateCommonControlWord("wbmbitspixel", 2147483652u),
		CreateCommonControlWord("wbmplanes", 2147483652u),
		CreateCommonControlWord("wbmwidthbytes", 2147483652u),
		CreateCommonControlWord("webhidden", 258u),
		CreateCommonControlWord("widctlpar", 514u),
		CreateCommonDocPropsControlWord("widowctrl"),
		CreateCommonControlWord("windowcaption", 8196u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_WMETAFILE, "wmetafile", 2147483652u),
		CreateCommonControlWord("wpeqn", 67108866u),
		CreateCommonDocPropsControlWord("wpjst"),
		CreateCommonDocPropsControlWord("wpsp"),
		CreateCommonDocPropsControlWord("wraptrsp"),
		CreateCommonControlWord("xe", 268435464u),
		CreateCommonControlWord("xef", 268435460u),
		CreateCommonControlWord("yr", 1073741828u),
		CreateCommonControlWord("yxe", 268435458u),
		CreateCommonControlWord("zwbo", 16u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_ZWJ, "zwj", 16u),
		CreateCommonControlWord("zwnbo", 16u),
		new RtfControlWordInfo(RtfControlWord.Ctrl_ZWNJ, "zwnj", 16u)
	};

	[MethodImpl(MethodImplOptions.NoInlining)]
	private static RtfControlWordInfo CreateCommonControlWord(string controlName, uint flags)
	{
		return new RtfControlWordInfo(RtfControlWord.Ctrl_Unknown, controlName, flags);
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private static RtfControlWordInfo CreateCommonDocPropsControlWord(string controlName)
	{
		return new RtfControlWordInfo(RtfControlWord.Ctrl_Unknown, controlName, 8194u);
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private static RtfControlWordInfo CreateCommonDrawObjControlWord(string controlName)
	{
		return new RtfControlWordInfo(RtfControlWord.Ctrl_Unknown, controlName, 536870914u);
	}
}
